### ISSUE TITLE
诶斗 你是誰啊XDD

### ISSUE THREAD

**Issue by ToooAir** [weiclaire/jerry_web_test#3]
我是助教 
中午忘了問名字
我得把你的名字和github帳號配對
之後才方便改作業
看到麻煩回覆一下哈哈哈

你同一組的也能一起給我

**Comment by weiclaire** [comment]
啊啊啊
不好意思我今天才看到
姓名：李冠葦  台師大  40443127s
github帳號：weiclaire
姓名：林玉庭
github帳號：0222826398
姓名：吳友倫
github帳號：wuoillan
姓名：(姓忘記了?@@)靖尹
github帳號：camelliabunny

**Comment by ToooAir** [comment]
好囉 我幫你們把帳號跟repo記下來了
(其實昨天就用完了)
分數也幫你們打了
等下星期上課就好
也能先看看老師的PDF喔
